package threads;

public class ResultTask extends Thread {
    public void run(){
        System.out.println("Result generated by:"+Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t= new ResultTask();
        t.run();
        t.start();
    }
}